### PR TITLE
Fix regular expressions

### PR DESCRIPTION
**Pull request by albert-ziegler**
I really don't want to be a bother, but could I just ask whether #98 was closed by mistake?

If not, it would be very helpful to me to understand why:
* Is it actually deliberate to have regular expressions that only look like they'd modify the string but actually don't? (This would be important false-positive info for us.)
* Was my PR description unclear? (This would be valuable info for me personally.)
* Or is there a different reason?

If yes: There's a couple of regexes that I'm pretty sure don't work as intended because of incorrect escaping and they are missing the global flag. These appear in several files. I've replaced them with the correct form to actually replace all instances of `]` by `\]` and `[` by `\[`.

### CODE REVIEW

**Comment by gajendran-egov** [comment]
Is this PR still valid, if yes, please rebase and submit it again. It will go to default reviwer

**Comment by albert-ziegler** [comment]
Thanks, yes it's still valid. I've rebased it.

**Comment by tarunlalwani** [comment]
@albert-ziegler, Sorry but we currently under some repo restricting and most of the files that this PR changes will get archived. So I am closing this pull request. We deal with the changes once the repo restricting completes. Thanks for you help

**Comment by albert-ziegler** [comment]
Sure, no worries :+1:

**Pull request closed without merging**
